In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import re

In [2]:
df_leads = pd.read_csv("~\\college stuff\\Internship 2025\\LPU Assignment MBA\\MBA Tech\\Performance_Marketing_leads.csv", encoding='latin1')

C:\Users\dynam\AppData\Local\Temp\ipykernel_17596\992354539.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_leads = pd.read_csv("~\\college stuff\\Internship 2025\\LPU Assignment MBA\\MBA Tech\\Performance_Marketing_leads.csv", encoding='latin1')

In [3]:
df_leads

,lead_id,created_time,ad_id,campaign_id,form_id,form_name,platform,name,email1,phone1,...,ug_or_pg_qualification,work_experience_1,mathematics_score,owner,city,opportunity_status,opportunity_mapped,utm_term,status,max_call_duration
0,l:895118632787497,29-11-2024 12:07,1.200000e+17,1.200000e+17,f:946834734166968,MBATech_C2_Program-new_Meta_110224,ig,Gyan Sagar Singh,gyansagarsingh@gmail.com,p:11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2fdc474d-31fd-4cb3-b5e4-9c03b4841499,02-01-2025 22:04,7.210000e+11,2.191242e+10,NaN,NaN,GoogleAds,Deep Kumar,deepkumar@gmail.com,0,...,NaN,NaN,NaN,Payal Gupta,NaN,NaN,Mapped,mba degree programs,Lost,NaN
2,c3c3960a-3c19-4824-95db-bc6a5df5db86,22-12-2024 12:17,7.210000e+11,2.191242e+10,NaN,NaN,GoogleAds,Sagar Mr,sagarmr@gmail.com,1918755051,...,NaN,NaN,NaN,Akshay Manhas,NaN,NaN,Mapped,mba degree programs,Lost,NaN
3,35275acf-6604-4e85-8414-5a33d3f171e5,10-01-2025 22:28,7.210000e+11,2.191242e+10,NaN,NaN,GoogleAds,ray jyoit ray jyoit,rayjyoitrayjyoit@gmail.com,1191911911,...,NaN,NaN,NaN,Zoya Zamal,NaN,NaN,Mapped,NaN,Lost,NaN
4,bf299df5-fe65-4b4f-b906-1a318b94ea4b,03-01-2025 22:40,7.210000e+11,2.191242e+10,NaN,NaN,GoogleAds,Love Kesh,lovekesh@gmail.com,1917087969,...,NaN,NaN,NaN,Zoya Zamal,NaN,NaN,Mapped,mba degree programs,Lost,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20060,1dad7269-f65a-46fd-a76d-8600bf65c004-6,02-01-2025 14:15,5.244873e+08,3.408116e+08,10091086,MBATech_C2_Program_LinkedIn_230924,LinkedIn,Devavrat Sharma,devavratsharma@gmail.com,9001750197,...,NaN,NaN,NaN,Vinti,Jaipur,NaN,Mapped,NaN,Open,23.0
20061,l:579525214711938,02-01-2025 19:48,1.200000e+17,1.200000e+17,f:934293608524038,MBATech_C2_Program_Meta_200924,ig,Surendra Singh,surendrasingh@gmail.com,9917119585,...,NaN,NaN,NaN,Monalisa das,Meerut City,NaN,Mapped,NaN,Open,3.0
20062,l:1323141678713428,03-01-2025 13:55,1.200000e+17,1.200000e+17,f:946834734166968,MBATech_C2_Program-new_Meta_110224,ig,Poonam Jyotshi,poonamjyotshi@gmail.com,8690191769,...,NaN,NaN,NaN,Monalisa das,NaN,NaN,Mapped,NaN,Open,20.0
20063,l:1092199192404421,11-01-2025 15:35,1.200000e+17,1.200000e+17,f:934293608524038,MBATech_C2_Program_Meta_200924,ig,Lokesh Kumar,lokeshkumar@gmail.com,9871158611,...,NaN,NaN,NaN,Payal Gupta,Noida,NaN,Mapped,NaN,Open,54.0
20064,a86db647-d221-4d34-a9c7-e013258e6b6c-3,12-10-2024 02:09,5.245299e+08,3.407865e+08,10091086,MBATech_C2_Program_LinkedIn_230924,LinkedIn,Tarique Anwar,tariqueanwar@gmail.com,9861186161,...,NaN,NaN,NaN,Akshit Mittal,Ranchi,Not Interested,Mapped,NaN,Lost,28.0

In [4]:
df_leads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20065 entries, 0 to 20064
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   lead_id                 20065 non-null  object
 1   created_time            20065 non-null  object
 2   ad_id                   20030 non-null  float64
 3   campaign_id             20030 non-null  float64
 4   form_id                 19883 non-null  object
 5   form_name               19883 non-null  object
 6   platform                20064 non-null  object
 7   name                    20065 non-null  object
 8   email1                  20065 non-null  object
 9   phone1                  20065 non-null  object
 10  graduation_degree       20065 non-null  object
 11  graduation_percentage   19892 non-null  object
 12  work_experience         20065 non-null  object
 13  upload_date             19883 non-null  object
 14  column15                0 non-null      float64
 15  contacted               17241 non-null  object
 16  mapped                  0 non-null      float64
 17  mapped2                 19190 non-null  object
 18  lead_stage              19190 non-null  object
 19  token_paid              57 non-null     float64
 20  Unnamed: 20             0 non-null      float64
 21  ad_set_name             0 non-null      float64
 22  ad_set_id               17923 non-null  float64
 23  first_call              17125 non-null  object
 24  outbound_calls          0 non-null      float64
 25  full_payment            0 non-null      float64
 26  test_sent               0 non-null      float64
 27  test_result             0 non-null      float64
 28  candidate_id            2133 non-null   object
 29  answered                17192 non-null  object
 30  mapped_in               0 non-null      float64
 31  lsq_created_date        19141 non-null  object
 32  last_call_date          17250 non-null  object
 33  new_cgpa                304 non-null    float64
 34  ug_or_pg_qualification  291 non-null    object
 35  work_experience_1       247 non-null    float64
 36  mathematics_score       0 non-null      float64
 37  owner                   19190 non-null  object
 38  city                    10921 non-null  object
 39  opportunity_status      6221 non-null   object
 40  opportunity_mapped      19079 non-null  object
 41  utm_term                146 non-null    object
 42  status                  19053 non-null  object
 43  max_call_duration       11615 non-null  float64
dtypes: float64(17), object(27)
memory usage: 6.7+ MB

In [5]:
df_leads.sample(10)

,lead_id,created_time,ad_id,campaign_id,form_id,form_name,platform,name,email1,phone1,...,ug_or_pg_qualification,work_experience_1,mathematics_score,owner,city,opportunity_status,opportunity_mapped,utm_term,status,max_call_duration
7063,l:366489019854308,05-12-2024 20:25,1.200000e+17,1.200000e+17,f:946834734166968,MBATech_C2_Program-new_Meta_110224,ig,Bhumi,bhumi@gmail.com,8611061118,...,NaN,NaN,NaN,Simran Rana,NaN,NaN,Mapped,NaN,Lost,47.0
13772,l:593796286391013,24-12-2024 14:50,1.200000e+17,1.200000e+17,f:946834734166968,MBATech_C2_Program-new_Meta_110224,ig,Kunal Kumar,kunalkumar@gmail.com,7906199719,...,NaN,NaN,NaN,Vinti,NaN,NaN,Mapped,NaN,Lost,82.0
8325,l:2164608543935209,12-12-2024 22:15,1.200000e+17,1.200000e+17,f:946834734166968,MBATech_C2_Program-new_Meta_110224,ig,Sarada Srirama,saradasrirama@gmail.com,9908069665,...,NaN,NaN,NaN,Akshay Manhas,NaN,NaN,Mapped,NaN,Lost,41.0
14051,l:1099545088488919,03-12-2024 00:07,1.200000e+17,1.200000e+17,f:946834734166968,MBATech_C2_Program-new_Meta_110224,ig,Sushant Surajkar,sushantsurajkar@gmail.com,9015071970,...,NaN,NaN,NaN,Sangeeta Haldar,NaN,NaN,Mapped,NaN,Lost,34.0
981,l:911579350399360,17-10-2024 21:38,1.200000e+17,1.200000e+17,f:934293608524038,MBATech_C2_Program_Meta_200924,ig,Er Naveen Kumar Sharma,ernaveenkumarsharma@gmail.com,8171181016,...,NaN,NaN,NaN,Akshay Manhas,Nawabganj,Did Not Enquired,Mapped,NaN,Lost,NaN
11954,l:455681743948500,11-12-2024 16:20,1.200000e+17,1.200000e+17,f:934293608524038,MBATech_C2_Program_Meta_200924,ig,Sailatha Ramesh,sailatharamesh@gmail.com,8555911116,...,NaN,NaN,NaN,Zoya Zamal,Bangalore,NaN,Mapped,NaN,Lost,34.0
1518,l:1458626351496631,15-10-2024 07:28,1.200000e+17,1.200000e+17,f:934293608524038,MBATech_C2_Program_Meta_200924,ig,itz-Masroor,itz-masroor@gmail.com,8187171165,...,NaN,NaN,NaN,Akshit Mittal,Kishanganj,Not Interested,Mapped,NaN,Lost,NaN
4601,l:1513337882697671,31-12-2024 23:26,1.200000e+17,1.200000e+17,f:946834734166968,MBATech_C2_Program-new_Meta_110224,ig,Komal Karvande,komalkarvande@gmail.com,7666711979,...,NaN,NaN,NaN,Zoya Zamal,NaN,NaN,Mapped,NaN,Lost,26.0
12801,l:889510192968137,08-12-2024 09:35,1.200000e+17,1.200000e+17,f:934293608524038,MBATech_C2_Program_Meta_200924,ig,Jaikishore Singh,jaikishoresingh@gmail.com,7191010810,...,NaN,NaN,NaN,Rishi Joshi,Noida,NaN,Mapped,NaN,Lost,NaN
2854,l:1060580302376196,16-10-2024 00:04,1.200000e+17,1.200000e+17,f:934293608524038,MBATech_C2_Program_Meta_200924,ig,RD,rd@gmail.com,9166711511,...,NaN,NaN,NaN,Akshit Mittal,Udaipur,Not Interested,Mapped,NaN,Lost,NaN

Let's first Check the data types of the columns given and work on them if they are not correct.

In [6]:
df_leads['created_time'] = pd.to_datetime(df_leads['created_time'], dayfirst=True)

In [7]:
for i in range(len(df_leads['phone1'])):
    if len(str(df_leads.loc[i, "phone1"])) != 10:
        df_leads.loc[i, "phone1"] = np.nan

In [8]:
df_leads['phone1'].isnull().sum()

np.int64(90)

In [9]:
df_leads['phone1'] = pd.to_numeric(df_leads['phone1'], errors='coerce')

In [10]:
df_leads['upload_date'] = pd.to_datetime(df_leads['upload_date'], dayfirst=True)

In [11]:
df_leads.drop(columns=['column15'], inplace=True)

In [12]:
for i in df_leads['graduation_percentage'].dropna():
    try:
        i = int(i)
    except ValueError:
        print(i)

100%
75%
50%
100%
50%
100%
100%
100%
80%

In [13]:
for i in range(len(df_leads['graduation_percentage'])):
    if isinstance(df_leads.loc[i, "graduation_percentage"], str):
        if '%' in df_leads.loc[i, "graduation_percentage"]:
            df_leads.loc[i, "graduation_percentage"] = df_leads.loc[i, "graduation_percentage"].replace('%', '')
        elif df_leads.loc[i, "graduation_percentage"].isdigit():
            df_leads.loc[i, "graduation_percentage"] = int(df_leads.loc[i, "graduation_percentage"])
        else:
            df_leads.loc[i, "graduation_percentage"] = np.nan

In [14]:
df_leads['graduation_percentage'] = pd.to_numeric(df_leads['graduation_percentage'], errors='coerce')

In [15]:
for i in range(len(df_leads['work_experience'])):
    try:
        df_leads.loc[i, 'work_experience'] = re.search(r'\d+', str(df_leads.loc[i, 'work_experience'])).group(0)
        if df_leads.loc[i, 'work_experience'] == '0':
            df_leads.loc[i, 'work_experience'] = 0
    except AttributeError:
        df_leads.loc[i, 'work_experience'] = np.nan

In [16]:
df_leads['work_experience'] = pd.to_numeric(df_leads['work_experience'], errors='coerce')

In [17]:
df_leads.drop(columns=['mapped'], inplace=True)

In [18]:
df_leads.rename(columns={'mapped2': 'mapped'}, inplace=True)

In [19]:
df_leads['token_paid'].value_counts()

token_paid
1.0    57
Name: count, dtype: int64

In [20]:
for i in range(len(df_leads['token_paid'])):
    if pd.isna(df_leads.loc[i, 'token_paid']):
        df_leads.loc[i, 'token_paid'] = 0

In [21]:
df_leads['token_paid'].value_counts()

token_paid
0.0    20008
1.0       57
Name: count, dtype: int64

In [22]:
df_leads.drop(columns=['Unnamed: 20'], inplace=True)

In [23]:
df_leads['first_call'].sample(10)

3505     05:22.0
15801    11:02.0
3450     15:00.0
2530         NaN
13375    04:26.0
17065    30:01.0
12226    33:26.0
16405    21:05.0
19430    38:00.0
17007    35:00.0
Name: first_call, dtype: object

In [24]:
def convert_to_seconds(x):
    try:
        if pd.isnull(x):
            return np.nan
        # Split mm:ss format
        parts = str(x).split(":")
        if len(parts) == 2:
            minutes = int(parts[0])
            seconds = float(parts[1])
            return minutes * 60 + seconds
        return np.nan
    except:
        return np.nan

In [25]:
df_leads['first_call_seconds'] = df_leads['first_call'].apply(convert_to_seconds)

In [26]:
df_leads[df_leads['first_call_seconds'] == 0]['first_call_seconds'].count()

np.int64(44)

In [27]:
df_leads['answered'].value_counts()

answered
Answered      8930
Unanswered    8156
unanswered      78
answered        28
Name: count, dtype: int64

In [28]:
df_leads['answered'] = df_leads['answered'].apply(
    lambda x: str(x).capitalize() if pd.notna(x) else x
)

In [29]:
df_leads['answered'].value_counts()

answered
Answered      8958
Unanswered    8234
Name: count, dtype: int64

In [30]:
df_leads['answered'].isna().sum()

np.int64(2873)

In [31]:
df_leads['lsq_created_date'] = pd.to_datetime(df_leads['lsq_created_date'], dayfirst=True)

In [32]:
df_leads['last_call_date'] = pd.to_datetime(df_leads['last_call_date'], dayfirst=True)

In [33]:
df_leads[df_leads['new_cgpa'].notna()]['new_cgpa'].value_counts()

new_cgpa
0.00     74
70.00    24
7.00     24
8.00     19
60.00    16
         ..
7.80      1
81.00     1
7.96      1
56.00     1
7.20      1
Name: count, Length: 63, dtype: int64

In [34]:
df_leads['ug_or_pg_qualification'].value_counts()

ug_or_pg_qualification
UG                                                                                                                         58
btech                                                                                                                      22
ug                                                                                                                         21
na                                                                                                                         15
0                                                                                                                          12
                                                                                                                           ..
bsc + mca                                                                                                                   1
BCA Graduate                                                                                                                1
Candidate have 6years of WE in Automobile, B tech 70% agg looking for MBA in Marketing disconnected as I mentioned fees     1
btech ele                                                                                                                   1
Candidate have 10years of WE in IT Recruitment, Bachelor's PGDM above 65% agg                                               1
Name: count, Length: 117, dtype: int64

In [35]:
df_leads[
    df_leads['work_experience_1'].notna() & df_leads['work_experience'].isna()
][['name', 'work_experience', 'work_experience_1']]

Empty DataFrame
Columns: [name, work_experience, work_experience_1]
Index: []

In [36]:
df_leads['owner'].isna().sum()

np.int64(875)

In [37]:
df_leads['city'] = df_leads['city'].apply(lambda x: str(x).capitalize() if pd.notna(x) else x)

In [38]:
df_leads['opportunity_status'].value_counts()

opportunity_status
Not Interested              1797
Never Picked Up             1075
Not Eligible                 787
Did Not Enquired             586
Did Not Picked               572
Call Back Later              391
Warm                         357
Invalid                      262
New Enquiry                  205
Call Not Connected            69
Wrong Number                  64
Dropped                       13
Learner Drop                   9
Future Prospect                8
Learner Enrolled               4
Interview Scheduled            4
Test Scheduled                 4
Interview Cleared              4
Waiting for Offer Letter       3
Offer Letter Released          2
Hot                            2
Test                           1
Token Link Sent                1
Applicant                      1
Name: count, dtype: int64

In [39]:
df_leads['opportunity_mapped'].value_counts()

opportunity_mapped
Mapped    19079
Name: count, dtype: int64

In [40]:
df_leads['utm_term'].value_counts()

utm_term
mba degree programs    127
iit jodhpur mba          8
mba courses              5
mba program              3
mba online               1
1.20E+17                 1
mba degree               1
Name: count, dtype: int64

In [41]:
df_leads['status'].value_counts()

status
Lost    15915
Open     3121
Won        17
Name: count, dtype: int64

In [42]:
df_leads['max_call_duration'].value_counts()

max_call_duration
29.0      176
2.0       172
32.0      167
30.0      166
37.0      163
         ...
376.0       1
900.0       1
729.0       1
1203.0      1
799.0       1
Name: count, Length: 1110, dtype: int64

In [43]:
df_leads.drop(columns=['ad_set_name','test_sent', 'outbound_calls','full_payment','test_result','mapped_in','mathematics_score','work_experience_1'], inplace=True)

In [44]:
df_leads.drop_duplicates(inplace=True)

In [45]:
df_leads['form_name'].value_counts()

form_name
MBATech_C2_Program-new_Meta_110224    8962
MBATech_C2_Program_Meta_200924        8962
MBATech_C2_Program_LinkedIn_230924    1939
Name: count, dtype: int64

In [46]:
# df_leads.to_csv("PML_cleaned.csv", index=False)

In [47]:
df_leads['graduation_degree'] = df_leads['graduation_degree'].apply(
	lambda x: "bca/bsc" if x == "bca_/_bsc" else x
)

In [48]:
df_leads['graduation_degree'] = df_leads['graduation_degree'].apply( lambda x: "mca/msc" if x == "mca_/msc" else x)

In [49]:
df_leads['graduation_degree'].sample(10)

3620     b.tech/be
5448       bca/bsc
14956    b.tech/be
12251    B.Tech/BE
3344        others
14232       others
19451    B.Tech/BE
17910      mca/msc
6017       bca/bsc
15586    b.tech/be
Name: graduation_degree, dtype: object

In [50]:
df_leads['contacted'].fillna('Not Contacted', inplace=True)

C:\Users\dynam\AppData\Local\Temp\ipykernel_17596\1209012790.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_leads['contacted'].fillna('Not Contacted', inplace=True)

In [51]:
df_temp = df_leads[(df_leads['mapped'].isna())&(df_leads['owner'].isna())]

In [52]:
df_temp[['opportunity_mapped']].isna().sum()

opportunity_mapped    874
dtype: int64

In [53]:
df_leads['lead_stage'].isna().sum()

np.int64(874)

In [54]:
df_temp['lead_stage'].isna().sum()

np.int64(874)

In [55]:
df_leads['first_call'].isna().sum()

np.int64(2940)

In [56]:
df_leads['candidate_id'].isna().sum()

np.int64(17915)

In [57]:
df_temp = df_leads[(df_leads['candidate_id'].notna())]

In [58]:
df_temp['lead_stage'].value_counts()

lead_stage
Not Interested           713
Never Picked Up          549
Not Eligible             228
Did Not Picked           192
Did Not Enquired         145
Invalid                   92
Call Back Later           55
New Enquiry               52
Wrong Number              34
Warm                      23
Call Not Connected        20
Dropped                    6
Learner Enrolled           4
Learner Drop               3
Never Picked up            3
Offer Letter Released      3
Future Prospect            3
Invalid phone number       2
Hot                        1
Token paid                 1
Test Scheduled             1
Name: count, dtype: int64

In [59]:
df_leads['answered'].isna().sum()

np.int64(2873)

In [60]:
df_leads['new_cgpa'].isna().sum()

np.int64(19742)

In [61]:
df_leads['ug_or_pg_qualification'].isna().sum()

np.int64(19755)

In [62]:
df_leads['owner'].value_counts()

owner
Akshit Mittal      2092
Sangeeta Haldar    1863
Monalisa das       1682
Akshay Manhas      1673
Vinti              1659
                   ...
Abid Bhat             1
Rishab Shahi          1
Rahul D               1
Mamta Sahani          1
Shivam Katiyar        1
Name: count, Length: 71, dtype: int64

In [63]:
df_leads['city'].isna().sum()

np.int64(9144)

In [64]:
df_leads[['lead_stage', 'answered', 'mapped']][(df_leads['lead_stage'].isna()) & (df_leads['answered'].notna())]

      lead_stage    answered mapped
2187         NaN  Unanswered    NaN
3002         NaN  Unanswered    NaN
3003         NaN  Unanswered    NaN
3004         NaN  Unanswered    NaN
3005         NaN  Unanswered    NaN
...          ...         ...    ...
19965        NaN  Unanswered    NaN
19995        NaN    Answered    NaN
19996        NaN  Unanswered    NaN
20056        NaN    Answered    NaN
20058        NaN    Answered    NaN

[396 rows x 3 columns]

In [65]:
df_leads['answered'].isnull().sum()

np.int64(2873)

In [66]:
df_leads['mapped'].fillna('Not Mapped', inplace=True)

C:\Users\dynam\AppData\Local\Temp\ipykernel_17596\2224478503.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_leads['mapped'].fillna('Not Mapped', inplace=True)

In [67]:
df_leads[['lead_stage', 'answered', 'mapped']][(df_leads['lead_stage'].isna()) & (df_leads['answered'].notna())]

      lead_stage    answered      mapped
2187         NaN  Unanswered  Not Mapped
3002         NaN  Unanswered  Not Mapped
3003         NaN  Unanswered  Not Mapped
3004         NaN  Unanswered  Not Mapped
3005         NaN  Unanswered  Not Mapped
...          ...         ...         ...
19965        NaN  Unanswered  Not Mapped
19995        NaN    Answered  Not Mapped
19996        NaN  Unanswered  Not Mapped
20056        NaN    Answered  Not Mapped
20058        NaN    Answered  Not Mapped

[396 rows x 3 columns]

In [68]:
df_leads['lead_stage'][df_leads['answered'] == "Unanswered"].value_counts()

lead_stage
Never Picked Up          3158
Not Interested           1502
Did Not Picked           1344
Invalid                   554
Not Eligible              434
Did Not Enquired          358
Call Back Later           199
Call Not Connected        183
Wrong Number               72
Warm                       68
New Enquiry                44
Future Prospect            23
Learner Drop               13
Dropped                    10
Offer Letter Released       8
Never Picked up             7
Test Scheduled              3
Invalid phone number        3
Learner Enrolled            3
Interview Cleared           2
Token Link Sent             2
Interview Scheduled         2
Hot                         1
Name: count, dtype: int64

In [69]:
df_leads['name']

0           Gyan Sagar Singh
1                 Deep Kumar
2                   Sagar Mr
3        ray jyoit ray jyoit
4                  Love Kesh
                ...
20060        Devavrat Sharma
20061         Surendra Singh
20062         Poonam Jyotshi
20063           Lokesh Kumar
20064          Tarique Anwar
Name: name, Length: 20045, dtype: object